name: Build and deploy to docker hub

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build node-23 + pnpm@9
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            NODE_VERSION=23.1.0-bullseye
            PNPM_VERSION=10.10.0
          file: Dockerfile
          push: true
          tags: |
            enix223/node-pnpm:23.1.0-bullseye_10.10.0

      - name: Build node-22 + pnpm@9
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            NODE_VERSION=22.11.0-bullseye
            PNPM_VERSION=10.10.0
          file: Dockerfile
          push: true
          tags: |
            enix223/node-pnpm:22.11.0-bullseye_10.10.0

      - name: Build node-20 + pnpm@9
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            NODE_VERSION=20.18.0-bullseye
            PNPM_VERSION=10.10.0
          file: Dockerfile
          push: true
          tags: |
            enix223/node-pnpm:20.18.0-bullseye_10.10.0

      - name: Build node-18 + pnpm@9
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            NODE_VERSION=18.20.4-bullseye
            PNPM_VERSION=10.10.0
          file: Dockerfile
          push: true
          tags: |
            enix223/node-pnpm:18.20.4-bullseye_10.10.0
